FROM python:3.11

WORKDIR /src
COPY ../requirements.txt /src/
COPY app /src/app
RUN pip install -r requirements.txt

CMD ["streamlit", "run", "app/streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
